@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyMyFitnessBuddy <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class MyFitnessBuddy
Class ReadOnlyMyFitnessBuddy
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Person {
Class Person
Class Profile
Class ID
Class Name
Class Height
Class UniquePersonList
}


Package Day {
Class Day
Class Weight
Class Date
Class UniqueDayList
}

Package Calorie {
Class Calorie
Class Input
Class Output
Class CalorieManager
Class CalorieCount
Class Time
Class Exercise
Class Food
}

Person "1"-> Profile
Profile --> Name
Profile --> ID
Profile --> Height
Profile --> Weight

CalorieManager "*"--> Input
CalorieManager "*"--> Output
Calorie <|-- Input
Calorie <|-- Output
Calorie *--> Time
Calorie *-> CalorieCount

Input *--> Food
Output *--> Exercise


Class HiddenOutside #FFFFFF
HiddenOutside ..> Model


MyFitnessBuddy .up.|> ReadOnlyMyFitnessBuddy

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" MyFitnessBuddy
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

MyFitnessBuddy *--> "1" UniquePersonList : filtered list

Person *--> "1" UniqueDayList

UniqueDayList o--> "*" Day
Day *--> CalorieManager
Day *--> Date
Day *--> Weight

@enduml
