@startuml
!include style.puml

skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface MyFitnessBuddyStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonMyFitnessBuddyStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> MyFitnessBuddyStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonMyFitnessBuddyStorage .left.|> MyFitnessBuddyStorage
JsonMyFitnessBuddyStorage .down.> JsonSerializableMyFitnessBuddyStorage
JsonSerializableMyFitnessBuddyStorage .right.> JsonAdaptedPerson
JsonAdaptedPerson .up.> JsonAdaptedProfile
JsonAdaptedPerson .right.> JsonAdaptedDay
JsonAdaptedDay .down.> JsonAdaptedCalorieManager
JsonAdaptedCalorieManager .left.> JsonAdaptedInput
JsonAdaptedCalorieManager .down.> JsonAdaptedOutput
@enduml
