@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package PopOutWindows <<Rectangle>>{
Class CalorieStatsWindow
Class WeightStatsWindow
Class CommanderBmiStatsWindow
Class HelpWindow
Class "{abstract}\nUiPart" as UiPart
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class MainWindow

@enduml
